//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IdEmpleado { get; set; }
        public string RFC { get; set; }
        public string NumeroEmpleado { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaControl { get; set; }
        public Nullable<decimal> Salario { get; set; }
    }
}
